"""Runtime config values."""

INTERNAL_WIDTH = 320
INTERNAL_HEIGHT = 180
SCALE_FACTOR = 4
WINDOW_WIDTH = INTERNAL_WIDTH * SCALE_FACTOR
WINDOW_HEIGHT = INTERNAL_HEIGHT * SCALE_FACTOR
FPS = 60
TITLE = "Fishing RPG"
